services:
  proj-522:
    image: charlene1010/term-deposit-predictor:e2f31b915e4658625124edd123b46e45cbee10da
    container_name: proj-522
    ports:
      - "8888:8888"
    volumes:
      - ./:/workplace
    stdin_open: true  # ← Allows interactive commands
    tty: true         # ← Proper terminal formatting
    platform: linux/amd64

