services:
  proj-522:
    image: charlene1010/term-deposit-predictor:2e3c23d7eef1c412165a899d522b059f385577b6
    container_name: proj-522
    ports:
      - "8888:8888"
    volumes: 
      - ./workplace:/workplace
    platform: linux/amd64

