services:
  proj-522:
    image: charlene1010/term-deposit-predictor:2338cd6affea378a1216c62552b2e965a18c77d4
    container_name: proj-522
    ports:
      - "8888:8888"
    volumes:
      - ./:/workplace
    stdin_open: true  # ← Allows interactive commands
    tty: true         # ← Proper terminal formatting
    platform: linux/amd64

